# Project-wide Gradle settings.

org.gradle.java.home=C:\\Users\\gkazanji\\.jdks\\jbr-21.0.11

# Specifies the JVM arguments used for the daemon process.
org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m

# When configured, Gradle will run in incubating parallel mode.
org.gradle.parallel=true

# AndroidX package structure
android.useAndroidX=true

# Enable AAPT2 PNG crunching
android.enablePngCrunchInReleaseBuilds=true

# Use this property to specify which architecture you want to build.
reactNativeArchitectures=armeabi-v7a,arm64-v8a,x86,x86_64

# Use this property to enable support to the new architecture.
newArchEnabled=true

# Use this property to enable or disable the Hermes JS engine.
hermesEnabled=true

# Use this property to enable edge-to-edge display support.
edgeToEdgeEnabled=true

# Enable GIF support in React Native images
expo.gif.enabled=true
# Enable webp support in React Native images
expo.webp.enabled=true
# Enable animated webp support
expo.webp.animated=false

# Enable network inspector
EX_DEV_CLIENT_NETWORK_INSPECTOR=true

# Use legacy packaging to compress native libraries in the resulting APK.
expo.useLegacyPackaging=false

# Specifies whether the app is configured to use edge-to-edge via the app config or plugin
expo.edgeToEdgeEnabled=true

# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
