services:
  - type: web
    name: pollinator-health-app
    runtime: static
    buildCommand: npm install && npx expo export --platform web
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
