import { ScrollView, Text, StyleSheet } from "react-native";

export default function TermsOfService() {
  return (
    <ScrollView contentContainerStyle={styles.container}>
      <Text style={styles.title}>Terms of Service</Text>

      <Text style={styles.section}>Acceptance of Terms</Text>
      <Text style={styles.text}>
        By accessing or using the website and mobile application (the "Service"), you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the Service. 
      </Text>

      <Text style={styles.section}>Account Registration</Text>
      <Text style={styles.text}>
        To use the Service, you must create an account. You agree to provide accurate and complete information during registration and to keep your account information up to date. You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. 
      </Text>

      <Text style={styles.section}>User Content and Submissions</Text>
      <Text style={styles.text}>
        When you submit sighting photographs, location data, or other content to the app, you retain ownership of your original content. However, by submitting content to the Service, you grant the app and Villanova University a non-exclusive, worldwide, royalty-free license to use, reproduce, display, and distribute your submissions for the purposes of: 
      </Text>
      <Text style={styles.bulletText}>
        Operating and improving the Service. 
      </Text>
      <Text style={styles.bulletText}>
        Conducting academic and ecological research on pollinators. 
      </Text>
      <Text style={styles.bulletText}>
        Publishing research findings (sighting data may be included in aggregated or anonymized form). 
      </Text>
      <Text style={styles.bulletText}>
        Contributing to public biodiversity databases and conservation efforts. 
      </Text>
      <Text style={styles.bulletText}>
        You represent that you have the right to submit any content you upload and that your submissions do not infringe on the rights of any third party. 
      </Text>

      <Text style={styles.section}>Acceptable Use </Text>
      <Text style={styles.text}>
        You agree not to: 
      </Text>
      <Text style={styles.bulletText}>
        Submit false, misleading, or fabricated sighting data. 
      </Text>
      <Text style={styles.bulletText}>
        Upload images that you do not have the right to share or that contain inappropriate content. 
      </Text>
      <Text style={styles.bulletText}>
        Harass, abuse, or threaten other users through comments or any other feature of the Service. 
      </Text>
      <Text style={styles.bulletText}>
        Attempt to interfere with, compromise, or disrupt the Service or its underlying infrastructure.  
      </Text>
      <Text style={styles.bulletText}>
        Use the Service for any unlawful purpose or in violation of any applicable laws or regulations. 
      </Text>
      <Text style={styles.bulletText}>
        Create multiple accounts to circumvent restrictions or manipulate data. 
      </Text>
      <Text style={styles.bulletText}>
        Use automated tools to scrape, collect, or mine data from the Service without prior written consent. 
      </Text>

      <Text style={styles.section}>AI-Powered Identifications </Text>
      <Text style={styles.text}>
        The species identifications provided by the Service are generated by machine learning models and should be treated as predictions, not definitive identifications. Confidence scores and composite ratings are provided to help assess the reliability of each prediction. We do not guarantee the accuracy of any automated identification. Users are encouraged to seek expert verification for critical determinations. 
      </Text>

      <Text style={styles.section}>Disclaimer of Warranties </Text>
      <Text style={styles.text}>
        The Service is provided "as is" and "as available" without warranties of any kind, either express or implied. We do not warrant that the Service will be uninterrupted, error-free, or free of harmful components. We make no warranties regarding the accuracy or reliability of any species identifications, data, or information obtained through the Service. 
      </Text>

      <Text style={styles.section}>Limitation of Liability </Text>
      <Text style={styles.text}>
        To the fullest extent permitted by law, Villanova University and their affiliates shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising out of or related to your use of the Service, including but not limited to reliance on species identifications provided by the platform. 
      </Text>

      <Text style={styles.section}>Termination</Text>
      <Text style={styles.text}>
        We reserve the right to suspend or terminate your account at our discretion if you violate these Terms or engage in conduct that we determine to be harmful to the Service or its community. You may delete your account at any time. Upon termination, your right to use the Service ceases immediately, though previously submitted sighting data may be retained for research purposes in accordance with our Privacy Policy. 
      </Text>
      
      <Text style={styles.section}>Changes to These Terms </Text>
      <Text style={styles.text}>
        We may update these Terms of Service from time to time. We will notify users of significant changes through the Service. Your continued use of the Service after updated terms are posted constitutes your acceptance of the revised terms. 
      </Text>

      <Text style={styles.section}>Governing Law </Text>
      <Text style={styles.text}>
        These Terms shall be governed by and construed in accordance with the laws of the State of Pennsylvania, United States, without regard to conflict of law principles.
      </Text>
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  container: {
    padding: 25,
    paddingTop: 50,
    paddingBottom: 50,
    backgroundColor: "#EAE2DC",
  },
  title: {
    fontSize: 24,
    fontWeight: "bold",
    marginBottom: 15,
  },
  section: {
    fontSize: 16,
    fontWeight: "600",
    marginTop: 15,
  },
  text: {
    fontSize: 14,
    marginTop: 5,
    lineHeight: 20,
    color: "#444",
  },
  bulletText: {
    marginTop: 5,
    paddingLeft: 20,
    flex: 1, 
    fontSize: 14,
    lineHeight: 20,
    color: "#444",
  },
});